# Generated by Django 3.1.7 on 2021-05-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='Family',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='Name',
        ),
    ]
