# Generated by Django 3.1.7 on 2021-03-30 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0002_concertmodel_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Family', models.CharField(max_length=100)),
                ('ProfileImage', models.ImageField(upload_to='ProfileImages/')),
                ('Gender', models.IntegerField(choices=[('Man', 'مرد'), ('Woman', 'زن')])),
            ],
        ),
        migrations.AddField(
            model_name='concertmodel',
            name='Poster',
            field=models.ImageField(null=True, upload_to='concertImages/'),
        ),
        migrations.CreateModel(
            name='ticketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketImage', models.ImageField(upload_to='TicketImages/')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('ProfileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.profilemodel')),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.timemodel')),
            ],
        ),
    ]
