# Generated by Django 3.1.7 on 2021-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0004_auto_20210401_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemodel',
            name='Status',
            field=models.IntegerField(choices=[(1, 'فروش بلیط شروع شده است'), (2, 'فروش بلیط تمام شده است'), (3, 'این سانی کنسل شده است'), (4, 'در حال فروش بلیط')], verbose_name='وضعیت'),
        ),
    ]
